name: Build Push Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: TangerieOrg/Workflows/.github/workflows/docker-build-push-nocheck.yml@main
    with:
      image_name: bettergpt
      registry_name: docker.tangerie.xyz
    secrets: inherit
    
  deploy:
    uses: TangerieOrg/Workflows/.github/workflows/docker-deploy.yml@main
    needs: 
      - build
    with:
      image_name: bettergpt
      registry_name: docker.tangerie.xyz
    secrets: inherit